# =====================================================
# 🚀 AUTH SERVICE – KUBERNETES DEPLOYMENT
# =====================================================

apiVersion: apps/v1                 # Kubernetes API version for Deployment
kind: Deployment                   # Resource type

metadata:
  name: auth-deployment            # Deployment name
  labels:
    app: auth-service              # Label for grouping

spec:
  replicas: 1                      # Number of pods (can scale later)

  selector:
    matchLabels:
      app: auth-service            # Must match pod labels

  template:
    metadata:
      labels:
        app: auth-service          # Pod label

    spec:
      containers:
        - name: auth-container     # Container name

          # 🔥 FINAL FIX → NEW SHA IMAGE (VERY IMPORTANT) 
          image: asia-south1-docker.pkg.dev/backend-auth-service-494704/auth-repo/auth-service:99efa9f199464d3602aa9cd04326257026c37ffe

          imagePullPolicy: Always  # Always pull latest image from registry

          ports:
            - containerPort: 5000  # App runs on port 5000

          env:
            - name: DATABASE_URL   # DB connection
              value: postgresql://postgres.ktwpojchloawedeiruvi:Raghunadh_1992@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require

            - name: JWT_SECRET_KEY # JWT key
              value: 9fA3xP@7Rk!2DqM8#ZbLw4^sC0N%YVJH

            - name: SECRET_KEY     # Flask secret
              value: super-secret-key

            - name: FLASK_ENV      # Environment mode
              value: Production