# =========================
# AUTH SERVICE DEPLOYMENT
# =========================

apiVersion: apps/v1                 # Kubernetes API version for Deployment
kind: Deployment                   # We are creating a Deployment resource

metadata:
  name: auth-deployment            # Name of the deployment
  labels:
    app: auth-service              # Label for identification

spec:
  replicas: 1                      # Number of pod instances (can scale later)

  selector:
    matchLabels:
      app: auth-service            # Must match pod labels

  template:
    metadata:
      labels:
        app: auth-service          # Label applied to pods

    spec:
      containers:
        - name: auth-container     # Container name inside pod

          # 🔥 FINAL IMAGE (SHA-BASED — PRODUCTION SAFE)
          image: asia-south1-docker.pkg.dev/backend-auth-service-494704/auth-repo/auth-service:277e918362c2fbc935254868543395ef828607e6

          imagePullPolicy: Always  # Always pull image from registry

          ports:
            - containerPort: 5000  # Flask/Gunicorn runs on port 5000

          env:
            - name: DATABASE_URL   # Database connection string
              value: postgresql://postgres.ktwpojchloawedeiruvi:Raghunadh_1992@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require

            - name: JWT_SECRET_KEY # JWT signing key
              value: 9fA3xP@7Rk!2DqM8#ZbLw4^sC0N%YVJH

            - name: SECRET_KEY     # Flask secret key
              value: super-secret-key

            - name: FLASK_ENV      # Environment mode
              value: Production