# =====================================================
# 🚀 CD - K8S AUTH SERVICE (FINAL)
# =====================================================

name: 🚀 CD - K8S Auth Service

on:
  push:
    branches:
      - feature/k8s-auth-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE Plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials auth-cluster \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      # 🔥 SHA BASED DEPLOY (FINAL FIX)
      - name: Deploy
        run: |
          IMAGE=asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/auth-service:k8s-${{ github.sha }}

          echo "🚀 Deploying $IMAGE"

          kubectl set image deployment/auth-deployment \
          auth-container=$IMAGE

          kubectl rollout status deployment/auth-deployment

          kubectl get pods -o wide
