# =====================================================
# 🚀 CD - K8S AUTH SERVICE (MANUAL + CRON ONLY)
# =====================================================

name: 🚀 CD - K8S Auth Service

on:
  # 🔘 Manual trigger (Run button)
  workflow_dispatch:

  # ⏰ Daily at 2 AM IST
  schedule:
    - cron: "30 20 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # -----------------------------------
      # 📥 Checkout repo
      # -----------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------------
      # 🔐 Authenticate to GCP
      # -----------------------------------
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # -----------------------------------
      # ☁️ Setup gcloud
      # -----------------------------------
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # -----------------------------------
      # 🔧 Install GKE auth plugin
      # -----------------------------------
      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # -----------------------------------
      # 🔗 Connect to GKE
      # -----------------------------------
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials my-cluster \
            --zone asia-south1-a \
            --project ${{ secrets.GCP_PROJECT_ID }}

      # -----------------------------------
      # 🚀 Deploy LATEST IMAGE (AUTO DETECT)
      # -----------------------------------
      - name: Get latest image tag
        id: latest
        run: |
          TAG=$(gcloud artifacts docker images list \
          asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/auth-repo/auth-service \
          --include-tags \
          --sort-by=~UPDATE_TIME \
          --limit=1 \
          --format="value(TAGS)")

          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      # -----------------------------------
      # 🚀 Deploy to Kubernetes
      # -----------------------------------
      - name: Deploy to Kubernetes
        run: |
          IMAGE=asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/auth-repo/auth-service:${{ steps.latest.outputs.TAG }}

          echo "🚀 Deploying latest image: $IMAGE"

          kubectl set image deployment/auth-deployment \
          auth-container=$IMAGE

          kubectl rollout status deployment/auth-deployment

          kubectl get pods -o wide
