name: 🚀 CD - Render Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Git Info
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "COMMIT_FULL=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

          echo "COMMIT_BODY<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%b >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Trigger Deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Wait
        run: sleep 30

      - name: Health Check
        run: |
          URL=https://backend-auth-service-ks6f.onrender.com

          for i in {1..25}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL || echo "000")
            if [ "$STATUS" = "200" ]; then exit 0; fi
            sleep 10
          done

          exit 1